server: { port: 8080 }
spring:
  application: { name: api-gateway }
  cloud:
    gateway:
      discovery: { locator: { enabled: true, lower-case-service-id: true } }
      routes:
        - id: auth
          uri: lb://auth-service
          predicates:
            - "Path=/auth/**"
        - id: investor
          uri: lb://investor-service
          predicates:
            - "Path=/investors/**,/bank-mandates/**,/nominees/**,/kyc-documents/**"
        - id: scheme
          uri: lb://scheme-service
          predicates:
            - "Path=/schemes/**"
        - id: folio
          uri: lb://folio-service
          predicates:
            - "Path=/folios/**"
        - id: transaction
          uri: lb://transaction-service
          predicates:
            - "Path=/transactions/**"
        - id: statement
          uri: lb://statement-service
          predicates:
            - "Path=/statements/**"
        - id: investor-openapi
          uri: lb://investor-service
          predicates:
            - "Path=/openapi/investor"
          filters:
            - "SetPath=/v3/api-docs"
        - id: auth-openapi
          uri: lb://auth-service
          predicates:
            - "Path=/openapi/auth"
          filters:
            - "SetPath=/v3/api-docs"
        - id: scheme-openapi
          uri: lb://scheme-service
          predicates:
            - "Path=/openapi/scheme"
          filters:
            - "SetPath=/v3/api-docs"
        - id: folio-openapi
          uri: lb://folio-service
          predicates:
            - "Path=/openapi/folio"
          filters:
            - "SetPath=/v3/api-docs"
        - id: transaction-openapi
          uri: lb://transaction-service
          predicates:
            - "Path=/openapi/transaction"
          filters:
            - "SetPath=/v3/api-docs"
        - id: statement-openapi
          uri: lb://statement-service
          predicates:
            - "Path=/openapi/statement"
          filters:
            - "SetPath=/v3/api-docs"
        - id: discovery-openapi
          uri: http://localhost:8761
          predicates:
            - "Path=/openapi/discovery"
          filters:
            - "SetPath=/v3/api-docs"
eureka: { client: { registry-fetch-interval-seconds: 5, service-url: { defaultZone: http://localhost:8761/eureka/ } } }
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    urls:
      - { name: API Gateway, url: /v3/api-docs }
      - { name: Auth Service, url: /openapi/auth }
      - { name: Discovery Server, url: /openapi/discovery }
      - { name: Investor Service, url: /openapi/investor }
      - { name: Scheme Service, url: /openapi/scheme }
      - { name: Folio Service, url: /openapi/folio }
      - { name: Transaction Service, url: /openapi/transaction }
      - { name: Statement Service, url: /openapi/statement }
fundwise:
  jwt:
    issuer: fundwise
    secret: ${AUTH_JWT_SECRET:fundwise-local-development-secret-change-me-2026}
