server:
  port: 8082
spring:
  application:
    name: scheme-service
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/fundwise_schema?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    open-in-view: false
  sql:
    init:
      mode: always
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/