define(['ojs/ojcontext', 'knockout', 'ojs/ojknockout'], function (Context, ko) {
  'use strict';

  // The OJet dev server runs on 8000. APIs are exposed through the gateway on 8080
  // (the gateway then routes /investors to the investor service on 8081).
  const API = window.FUNDWISE_API_BASE || 'http://localhost:8080';
  const SESSION_KEY = 'fundwise-investor-session';
  const money = new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 });
  const number = new Intl.NumberFormat('en-IN', { maximumFractionDigits: 2 });
  const date = new Intl.DateTimeFormat('en-IN', { dateStyle: 'medium' });

  function text(value) { return String(value == null ? '' : value).replace(/[&<>'"]/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' }[c])); }
  function initials(value) { return String(value || 'FW').split(/\s+/).filter(Boolean).slice(0, 2).map(v => v[0]).join('').toUpperCase(); }
  function formatMoney(value) { return money.format(Number(value || 0)); }
  function formatDate(value) { return value ? date.format(new Date(value)) : '—'; }
  function route() { return (location.hash || '#/').replace(/^#\/?/, '').split('?')[0] || 'home'; }
  function own(items, investorId) { return (Array.isArray(items) ? items : []).filter(item => String(item.investorId) === String(investorId)); }
  function folioCode(investorId, schemeId) { return `FW${String(investorId).padStart(4, '0')}${String(schemeId).padStart(3, '0')}${String(Date.now()).slice(-4)}`; }

  async function request(path, options) {
    const response = await fetch(`${API}${path}`, {
      cache: 'no-store',
      headers: { 'Content-Type': 'application/json', ...(options && options.headers || {}) },
      ...options
    });
    if (!response.ok) {
      let message = `Request failed (${response.status})`;
      try { const body = await response.json(); message = body.message || body.error || message; } catch (_) { /* retain status message */ }
      throw new Error(message);
    }
    return response.status === 204 ? null : response.json();
  }

  function ControllerViewModel() {
    const self = this;
    self.pageHtml = ko.observable('');
    self.session = ko.observable(readSession());
    self.data = { investor: null, folios: [], schemes: [], transactions: [], statements: [], banks: [], nominees: [] };
    self.notice = '';

    function readSession() {
      try { return JSON.parse(sessionStorage.getItem(SESSION_KEY)); } catch (_) { return null; }
    }
    function writeSession(investor) {
      const safe = { id: investor.id, fullName: investor.fullName, email: investor.email };
      sessionStorage.setItem(SESSION_KEY, JSON.stringify(safe)); self.session(safe);
    }
    function clearSession() { sessionStorage.removeItem(SESSION_KEY); self.session(null); }
    function signedIn() { return self.session() && self.session().id; }
    function go(destination) { location.hash = `#/${destination}`; }
    function navLink(to, label, icon) { return `<a class="side-link ${route() === to ? 'active' : ''}" href="#/${to}"><span>${icon}</span>${label}</a>`; }
    function toast(message, type) { self.notice = `<div class="toast ${type || ''}">${text(message)}</div>`; render(); window.setTimeout(() => { self.notice = ''; render(); }, 4200); }

    async function loadInvestorData() {
      const session = self.session();
      if (!session) return;
      const investor = await request(`/investors/${encodeURIComponent(session.id)}`);
      // Keep the identity returned by the service tied to the session before using any related data.
      if (String(investor.id) !== String(session.id)) throw new Error('Your secure session could not be verified. Please sign in again.');
      const [folios, schemes, banks, nominees, statementRecords] = await Promise.all([
        request('/folios'), request('/schemes'), request('/bank-mandates'), request('/nominees'), request('/statements')
      ]);
      const mine = own(folios, investor.id);
      const transactionLists = await Promise.all(mine.map(folio => request(`/transactions?folioId=${encodeURIComponent(folio.id)}`)));
      self.data = {
        investor, folios: mine, schemes: (schemes || []).filter(s => s.status === 'ACTIVE'),
        transactions: transactionLists.flat(), statements: (statementRecords || []).filter(s => mine.some(f => String(f.id) === String(s.folioId))),
        banks: own(banks, investor.id), nominees: own(nominees, investor.id)
      };
      writeSession(investor);
    }

    function shell(body) {
      const investor = self.data.investor || self.session();
      return `<div class="app-shell">
        <aside class="sidebar"><a class="brand" href="#/dashboard"><span class="brand-mark">F</span><span><strong>FundWise</strong><small>Private investing</small></span></a>
          <p class="nav-caption">My wealth</p><nav>${navLink('dashboard', 'Overview', '⌂')}${navLink('portfolio', 'Portfolio', '◈')}${navLink('discover', 'Discover funds', '◇')}${navLink('statements', 'Statements', '▤')}</nav>
          <p class="nav-caption">Account</p><nav>${navLink('profile', 'Profile & security', '◎')}</nav>
          <div class="sidebar-card"><span class="live-dot"></span><div><strong>Private portfolio</strong><small>Data scoped to your account</small></div></div>
          <button class="account-chip" data-action="logout"><span class="avatar">${initials(investor && investor.fullName)}</span><span><strong>${text(investor && investor.fullName || 'Investor')}</strong><small>Sign out</small></span></button>
        </aside>
        <section class="workspace"><header class="topbar"><button class="mobile-menu" data-action="toggle-menu" aria-label="Open menu">☰</button><div><span class="top-kicker">FundWise private client</span><strong>Your investments, clearly considered.</strong></div><div class="top-actions"><a class="quiet-link" href="#/profile">${text(investor && investor.email || '')}</a><span class="avatar small">${initials(investor && investor.fullName)}</span></div></header>
        <main class="content">${body}</main></section></div>${self.notice}`;
    }

    function landing() { return `<div class="landing"><header class="landing-header"><a class="brand light" href="#/"><span class="brand-mark">F</span><span><strong>FundWise</strong><small>Private investing</small></span></a><nav><a href="#/discover">Explore funds</a><a class="button ghost" href="#/login">Sign in</a><a class="button gold" href="#/register">Become a client</a></nav></header>
      <section class="hero"><div class="hero-copy"><p class="eyebrow">Designed for the deliberate investor</p><h1>Wealth deserves a <em>quieter</em> kind of confidence.</h1><p>Bring your long-term plans into focus with a considered view of your funds, holdings and statements.</p><div class="hero-actions"><a class="button gold" href="#/register">Open your view <span>→</span></a><a class="text-link" href="#/login">Already a client? Sign in</a></div><div class="trust-row"><span>◉ Private by design</span><span>◇ Clear portfolio views</span><span>✓ Statement-ready</span></div></div>
        <div class="hero-card"><p>Portfolio perspective</p><div class="hero-value">Built for <br><i>every chapter.</i></div><div class="accent-line"></div><div class="hero-stat"><span>Focused decisions</span><strong>One place for your wealth</strong></div></div></section>
      <section class="landing-points"><article><span>01</span><h2>Curated choices</h2><p>Discover active schemes with the detail required for a meaningful decision.</p></article><article><span>02</span><h2>Complete picture</h2><p>Keep your holdings and transactions in a portfolio you can understand at a glance.</p></article><article><span>03</span><h2>Record, retained</h2><p>Retrieve folio statements whenever you need a clean view of your activity.</p></article></section></div>`; }

    function auth(kind) { const register = kind === 'register'; return `<div class="auth-page"><a class="brand auth-brand" href="#/"><span class="brand-mark">F</span><span><strong>FundWise</strong><small>Private investing</small></span></a><div class="auth-layout"><section class="auth-intro"><p class="eyebrow">${register ? 'Begin a considered relationship' : 'Welcome back'}</p><h1>${register ? 'Your wealth, with room to breathe.' : 'Your portfolio is ready when you are.'}</h1><p>${register ? 'Create your client profile to access schemes, holdings and statements in one private space.' : 'Use the email and PAN tied to your FundWise profile to continue.'}</p><a href="#/${register ? 'login' : 'register'}" class="text-link">${register ? 'Already a client? Sign in' : 'New to FundWise? Create your profile'} →</a></section><section class="auth-card"><h2>${register ? 'Create your profile' : 'Sign in securely'}</h2><p>${register ? 'A few details to establish your investor profile.' : 'We verify the details already held on your profile.'}</p><form data-form="${register ? 'register' : 'login'}">${register ? `<label>Full name<input name="fullName" required minlength="2" autocomplete="name"></label>` : ''}<label>Email address<input type="email" name="email" required autocomplete="email"></label>${register ? `<label>Mobile number<input name="phone" required pattern="[0-9]{10}" maxlength="10" inputmode="numeric" placeholder="10 digit mobile number"></label>` : ''}<label>PAN${register ? ' number' : ' verification'}<input name="panNumber" required pattern="[A-Za-z]{5}[0-9]{4}[A-Za-z]" maxlength="10" autocomplete="off" placeholder="ABCDE1234F"></label>${register ? `<label class="check"><input type="checkbox" required>I agree to the FundWise client terms and privacy notice.</label>` : ''}<button class="button primary wide" type="submit">${register ? 'Create private profile' : 'Continue to portfolio'} <span>→</span></button></form><small class="auth-fine">Your session is held only in this browser and ends when you close it.</small></section></div></div>`; }

    function dashboard() { const d = self.data, invested = d.transactions.filter(t => t.transactionType === 'PURCHASE' && t.status === 'COMPLETED').reduce((sum,t) => sum + Number(t.amount || 0),0), current = d.folios.reduce((sum,f) => sum + Number(f.currentValue || 0),0), change = current - invested; const activity = [...d.transactions].sort((a,b) => new Date(b.transactionDate) - new Date(a.transactionDate)).slice(0,4); return shell(`<div class="page-head"><div><p class="eyebrow">Portfolio overview</p><h1>Good ${new Date().getHours() < 12 ? 'morning' : 'afternoon'}, ${text((d.investor.fullName || '').split(' ')[0])}.</h1><p>Here is the considered view of your FundWise portfolio.</p></div><a class="button primary" href="#/discover">Explore opportunities <span>→</span></a></div><div class="metric-grid"><article class="metric-card featured"><span>Current value</span><strong>${formatMoney(current)}</strong><small>${change >= 0 ? '+' : ''}${formatMoney(change)} from recorded purchases</small></article><article class="metric-card"><span>Invested</span><strong>${formatMoney(invested)}</strong><small>Across ${d.folios.length} active folio${d.folios.length === 1 ? '' : 's'}</small></article><article class="metric-card"><span>Active funds</span><strong>${d.folios.length}</strong><small>Held in your portfolio</small></article><article class="metric-card"><span>Client status</span><strong class="status-word">${text(d.investor.status || 'ACTIVE')}</strong><small>Profile ready to invest</small></article></div><div class="dashboard-grid"><section class="card"><div class="section-head"><div><h2>Your holdings</h2><p>A concise view of where your capital sits today.</p></div><a href="#/portfolio" class="text-link">Full portfolio →</a></div>${holdingsTable(d.folios, d.schemes)}</section><section class="card"><div class="section-head"><div><h2>Recent activity</h2><p>Latest transaction records.</p></div><a href="#/statements" class="text-link">Statements →</a></div><div class="activity-list">${activity.length ? activity.map(t => `<div class="activity"><span class="activity-icon">${t.transactionType === 'PURCHASE' ? '↓' : '↗'}</span><span><strong>${text(t.transactionType)}</strong><small>${formatDate(t.transactionDate)} · ${text(t.status)}</small></span><strong>${formatMoney(t.amount)}</strong></div>`).join('') : empty('No transactions yet', 'Explore available funds to make your first investment.')}</div></section></div>`); }

    function holdingsTable(folios, schemes) { if (!folios.length) return empty('Your portfolio is waiting.', 'Explore available schemes and build your first position.', 'Explore funds'); return `<div class="table-wrap"><table><thead><tr><th>Fund</th><th>Folio</th><th>Units</th><th>Current value</th><th></th></tr></thead><tbody>${folios.map(f => { const scheme = schemes.find(s => String(s.id) === String(f.schemeId)); return `<tr><td><strong>${text(scheme && scheme.name || `Scheme #${f.schemeId}`)}</strong><small>${text(scheme && scheme.schemeType || 'Fund')}</small></td><td>${text(f.folioNumber)}</td><td>${number.format(Number(f.currentUnits || 0))}</td><td><strong>${formatMoney(f.currentValue)}</strong></td><td><a class="row-link" href="#/statements?folio=${encodeURIComponent(f.id)}">Statement →</a></td></tr>`; }).join('')}</tbody></table></div>`; }
    function portfolio() { return shell(`<div class="page-head"><div><p class="eyebrow">Your holdings</p><h1>A portfolio built around you.</h1><p>Only folios registered to your investor profile appear here.</p></div><a class="button primary" href="#/discover">Add an investment <span>→</span></a></div><section class="card">${holdingsTable(self.data.folios, self.data.schemes)}</section>`); }
    function discover() { const schemes = self.data.schemes; return shell(`<div class="page-head"><div><p class="eyebrow">Discover funds</p><h1>Consider your next position.</h1><p>Active FundWise schemes, ready to add to your portfolio.</p></div></div><div class="fund-grid">${schemes.length ? schemes.map(s => `<article class="fund-card"><div class="fund-top"><span class="fund-type">${text(s.schemeType)}</span><span class="scheme-code">${text(s.schemeCode)}</span></div><h2>${text(s.name)}</h2><p>Current NAV <strong>${formatMoney(s.currentNav)}</strong></p><dl><div><dt>Expense ratio</dt><dd>${number.format(Number(s.expenseRatio || 0))}%</dd></div><div><dt>Status</dt><dd class="ready">Available</dd></div></dl><button class="button primary wide" data-action="buy" data-scheme="${text(s.id)}">Invest in this fund <span>→</span></button></article>`).join('') : empty('No active schemes available', 'Please return later to see available opportunities.')}</div>`); }
    function profile() { const d = self.data; return shell(`<div class="page-head"><div><p class="eyebrow">Profile & security</p><h1>Your private client profile.</h1><p>Contact, banking and nominee details attached to your investor record.</p></div><button class="button" data-action="refresh">Refresh profile</button></div><div class="profile-grid"><section class="card profile-card"><div class="profile-hero"><span class="profile-avatar">${initials(d.investor.fullName)}</span><div><h2>${text(d.investor.fullName)}</h2><p>${text(d.investor.email)}</p><span class="badge">${text(d.investor.status)}</span></div></div><dl class="details"><div><dt>Mobile</dt><dd>${text(d.investor.phone || 'Not supplied')}</dd></div><div><dt>PAN</dt><dd>${text((d.investor.panNumber || '').slice(0,5))}••••${text((d.investor.panNumber || '').slice(-1))}</dd></div><div><dt>Investor ID</dt><dd>FW-${text(d.investor.id)}</dd></div></dl></section><section class="card"><div class="section-head"><div><h2>Bank mandate</h2><p>Linked account used for your investments.</p></div></div><div class="compact-list">${d.banks.length ? d.banks.map(b => `<div><span class="list-symbol">▣</span><span><strong>${text(b.bankName)}</strong><small>•••• ${text(String(b.accountNumber || '').slice(-4))} · ${text(b.accountType || 'SAVINGS')}</small></span></div>`).join('') : empty('No bank mandate on record', 'Please contact FundWise support to add one.')}</div></section><section class="card"><div class="section-head"><div><h2>Nominees</h2><p>Your recorded succession preferences.</p></div></div><div class="compact-list">${d.nominees.length ? d.nominees.map(n => `<div><span class="list-symbol">◎</span><span><strong>${text(n.fullName)}</strong><small>${text(n.relationship || 'Nominee')} · ${number.format(Number(n.allocationPercentage || 0))}% allocation</small></span></div>`).join('') : empty('No nominee recorded', 'Please contact FundWise support to add one.')}</div></section></div>`); }
    function statements() { const d = self.data; return shell(`<div class="page-head"><div><p class="eyebrow">Statements</p><h1>Your investment record, retained.</h1><p>Select one of your folios to view an activity statement.</p></div></div><section class="card"><div class="section-head"><div><h2>Available folios</h2><p>Statements are available only for folios you own.</p></div></div><div class="statement-list">${d.folios.length ? d.folios.map(f => { const scheme = d.schemes.find(s => String(s.id) === String(f.schemeId)); return `<div><span class="statement-icon">▤</span><span><strong>${text(scheme && scheme.name || 'FundWise scheme')}</strong><small>Folio ${text(f.folioNumber)} · ${formatMoney(f.currentValue)}</small></span><button class="button" data-action="statement" data-folio="${text(f.id)}">View statement</button></div>`; }).join('') : empty('No statements available yet', 'Your statements will appear once you hold a folio.')}</div></section><div id="statement-preview"></div>`); }
    function empty(title, detail, action) { return `<div class="empty"><span>◇</span><h3>${text(title)}</h3><p>${text(detail)}</p>${action ? `<a class="button primary" href="#/discover">${text(action)} →</a>` : ''}</div>`; }

    function buyDialog(schemeId) { const scheme = self.data.schemes.find(s => String(s.id) === String(schemeId)); if (!scheme) return; document.body.insertAdjacentHTML('beforeend', `<div class="dialog-backdrop" id="buyDialog"><div class="dialog"><button class="dialog-close" data-action="close-dialog" aria-label="Close">×</button><p class="eyebrow">New investment</p><h2>${text(scheme.name)}</h2><p>Current NAV: <strong>${formatMoney(scheme.currentNav)}</strong></p><form data-form="buy"><input type="hidden" name="schemeId" value="${text(scheme.id)}"><label>Investment amount<input name="amount" type="number" min="500" step="100" required placeholder="e.g. 25000" autofocus></label><p class="form-note">Your purchase will be recorded against your private investor profile. The displayed NAV is used to calculate units.</p><button class="button primary wide" type="submit">Confirm investment <span>→</span></button></form></div></div>`); }
    async function showStatement(folioId) { const folio = self.data.folios.find(f => String(f.id) === String(folioId)); if (!folio) { toast('That folio is not available in your portfolio.', 'error'); return; }
      try { const statement = await request(`/statements/folio/${encodeURIComponent(folio.id)}`); if (!statement.folio || String(statement.folio.investorId) !== String(self.session().id)) throw new Error('Statement ownership check failed.'); const target = document.querySelector('#statement-preview'); const rows = (statement.transactions || []).map(t => `<tr><td>${formatDate(t.transactionDate)}</td><td>${text(t.transactionType)}</td><td>${formatMoney(t.amount)}</td><td>${number.format(Number(t.units || 0))}</td></tr>`).join('') || `<tr><td colspan="4">No transaction records for this folio.</td></tr>`; target.innerHTML = `<section class="statement-sheet"><div class="statement-heading"><span class="brand-mark">F</span><div><p class="eyebrow">FundWise statement</p><h2>${text(statement.scheme && statement.scheme.name || 'Investment statement')}</h2><p>Folio ${text(statement.folio.folioNumber)} · Generated ${formatDate(statement.generatedAt)}</p></div><button class="button" data-action="print">Print</button></div><div class="statement-summary"><div><span>Current value</span><strong>${formatMoney(statement.folio.currentValue)}</strong></div><div><span>Current units</span><strong>${number.format(Number(statement.folio.currentUnits || 0))}</strong></div><div><span>Investor</span><strong>${text(statement.investor && statement.investor.fullName || '')}</strong></div></div><table><thead><tr><th>Date</th><th>Type</th><th>Amount</th><th>Units</th></tr></thead><tbody>${rows}</tbody></table></section>`; target.scrollIntoView({ behavior: 'smooth', block: 'start' }); } catch (error) { toast(error.message, 'error'); }
    }

    async function submit(form) { const kind = form.dataset.form, values = Object.fromEntries(new FormData(form)); const button = form.querySelector('[type="submit"]'); button.disabled = true;
      try { if (kind === 'login') { const investors = await request('/investors'); const email = String(values.email || '').trim().toLowerCase(), pan = String(values.panNumber || '').trim().toUpperCase(); const investor = (investors || []).find(i => String(i.email || '').toLowerCase() === email && String(i.panNumber || '').toUpperCase() === pan); if (!investor) throw new Error('We could not verify those details. Please check your email and PAN.'); writeSession(investor); await loadInvestorData(); go('dashboard'); }
        if (kind === 'register') { const investor = await request('/investors', { method: 'POST', body: JSON.stringify({ fullName: values.fullName.trim(), email: values.email.trim(), phone: values.phone.trim(), panNumber: values.panNumber.trim().toUpperCase(), status: 'ACTIVE' }) }); writeSession(investor); await loadInvestorData(); go('dashboard'); }
        if (kind === 'buy') { const scheme = self.data.schemes.find(s => String(s.id) === String(values.schemeId)); const amount = Number(values.amount); if (!scheme || !Number.isFinite(amount) || amount < 500) throw new Error('Enter an investment amount of at least ₹500.'); const units = Number((amount / Number(scheme.currentNav)).toFixed(4)); let folio = self.data.folios.find(f => String(f.schemeId) === String(scheme.id)); if (folio) { folio = await request(`/folios/${encodeURIComponent(folio.id)}`, { method: 'PUT', body: JSON.stringify({ investorId: self.session().id, schemeId: scheme.id, folioNumber: folio.folioNumber, status: 'ACTIVE', currentUnits: Number(folio.currentUnits || 0) + units }) }); } else { folio = await request('/folios', { method: 'POST', body: JSON.stringify({ investorId: self.session().id, schemeId: scheme.id, folioNumber: folioCode(self.session().id, scheme.id), status: 'ACTIVE', currentUnits: units }) }); } await request('/transactions', { method: 'POST', body: JSON.stringify({ folioId: folio.id, transactionType: 'PURCHASE', transactionDate: new Date().toISOString().slice(0, 10), amount, nav: Number(scheme.currentNav), units, targetSchemeId: null, status: 'COMPLETED' }) }); document.querySelector('#buyDialog')?.remove(); await loadInvestorData(); toast('Your investment has been recorded.', 'success'); go('portfolio'); }
      } catch (error) { toast(error.message || 'Something went wrong. Please try again.', 'error'); } finally { button.disabled = false; }
    }

    async function render() { const current = route(); if (['dashboard','portfolio','discover','profile','statements'].includes(current) && !signedIn()) { go('login'); return; } try { if (signedIn() && ['dashboard','portfolio','discover','profile','statements'].includes(current)) await loadInvestorData(); const page = current === 'login' ? auth('login') : current === 'register' ? auth('register') : current === 'dashboard' ? dashboard() : current === 'portfolio' ? portfolio() : current === 'discover' && signedIn() ? discover() : current === 'profile' ? profile() : current === 'statements' ? statements() : landing(); self.pageHtml(page); } catch (error) { clearSession(); self.pageHtml(auth('login')); toast(error.message || 'We could not load your private portfolio.', 'error'); } }

    document.addEventListener('submit', event => { const form = event.target.closest('form[data-form]'); if (form) { event.preventDefault(); submit(form); } });
    document.addEventListener('click', event => { const control = event.target.closest('[data-action]'); if (!control) return; const action = control.dataset.action; if (action === 'logout') { clearSession(); go('home'); } if (action === 'buy') buyDialog(control.dataset.scheme); if (action === 'close-dialog') document.querySelector('#buyDialog')?.remove(); if (action === 'statement') showStatement(control.dataset.folio); if (action === 'refresh') { render(); toast('Your profile has been refreshed.', 'success'); } if (action === 'print') window.print(); if (action === 'toggle-menu') document.querySelector('.sidebar')?.classList.toggle('open'); });
    window.addEventListener('hashchange', render);
    render();
    Context.getPageContext().getBusyContext().applicationBootstrapComplete();
  }
  return new ControllerViewModel();
});
